version: "3.7"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vc
      MYSQL_USER: vc
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dbnet
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dbnet
  backend:
    image: vc-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - dbnet
    depends_on:
      - db
      - redis
  frontend:
    image: vc-frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:80
    networks:
      - dbnet
    depends_on:
      - backend
networks:
  dbnet: